modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${license}"
issueTrackerURL = "https://github.com/Spock117/TriggerMobs/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/trigger-mobs"
logoFile = "assets/${mod_id}/icon.png"
credits = "${credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "triggermobs.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ntgl"
type = "required"
versionRange = "[${minecraft_version}-3.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "guardvillagers"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cgs"
type = "optional"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
